### ISSUE TITLE
rsync error: syntax or usage error (code 1) at main.c(1508) [sender=3.2.7]

### ISSUE THREAD

**Issue by shyding** [RsyncProject/rsync#502]
信息: Command-line: C:\Users\dsy\rsync4j\bin\sshpass.exe -p test -v C:\Users\dsy\rsync4j\bin\rsync.exe --verbose --debug=ALL --recursive --rsh="ssh  -p 22-l test" --partial --timeout=100000 --human-readable --progress test@100.0.160.15:/home/test/hehe.zip  /cygdrive/d/test/other/place
[sender] _exit_cleanup(code=1, file=main.c, line=1508): about to call exit(1)
[sender] send_msg_int(86, 1)
Unexpected remote arg: test@100.0.160.15:/home/test/hehe.zip
rsync error: syntax or usage error (code 1) at main.c(1508) [sender=3.2.7]

**Comment by WayneD** [comment]
You can't put colons into local file args unless they follow a `./`. Rsync doesn't support Windows-style file paths. If you're using Cygwin, use `/cygwin/c/Users/...` or wherever your drives are mounted. Another option is to create a script that converts file args from Window-style to Unix-style and then calls rsync.
