### ISSUE TITLE
Add support for --filter-from to match --include-from / --exclude-from / --files-from

### ISSUE THREAD

**Issue by minfrin** [RsyncProject/rsync#663]
In complex scripting cases, getting the escaping right on the --filter option becomes impractical.

Ideally there needs to be a --filter-from option to read the filters from a file, to avoid escaping issues.

**Comment by charmitro** [comment]
You can achieve the desired functionality without the need for a `--filter-from` option by using the `merge` filter rule within the existing `--filter` option. This will allow you to include filter rules from an external file,

Here's an example,
```shell
$ tree source
source
├── exclude_dir
│   ├── file3.txt
│   └── file4.tmp
├── file5.jpg
├── file6.tmp
└── include_dir
    ├── file1.txt
    └── file2.jpg

3 directories, 6 files

$ cat filter_file
+ /include_dir/**
- /exclude_dir/***
+ *.jpg
- *.tmp

$ rsync -av --filter='merge filter_file' source/ destination/
building file list ... done
created directory destination
./
file5.jpg
include_dir/
include_dir/file1.txt
include_dir/file2.jpg

sent 289 bytes  received 98 bytes  774.00 bytes/sec
total size is 0  speedup is 0.00

$ tree destination
destination
├── file5.jpg
└── include_dir
    ├── file1.txt
    └── file2.jpg

2 directories, 3 files
```

**Comment by minfrin** [comment]
In your example you have this:

```
--filter='merge filter_file'
```

In the above example you have a ' character, which is made necessary because of the presence of functionally significant whitespace. Both of these are difficult to script when you need to add escaping both the whitespace and the single quote through multiple layers of logic.

All of this pain goes away when you have --filter-from option, as per this issue.

**Comment by charmitro** [comment]
I generally agree that this can improve the use case, and the code for it is almost there:
https://github.com/RsyncProject/rsync/blob/f654e47691629c7516095518dec4234a689a8351/exclude.c#L1447

I have a work-in-progress tree for this, making it happen as seen below,
```shell
$ tree source
source
├── exclude_dir
│   ├── file3.txt
│   └── file4.tmp
├── file5.jpg
├── file6.tmp
└── include_dir
    ├── file1.txt
    └── file2.jpg

$ cat filter_file
+ /include_dir/**
- /exclude_dir/***
+ *.jpg
- *.tmp

$ ./rsync/rsync -av --filter-from=filter_file source/ destination/
sending incremental file list
created directory destination
./
file5.jpg
include_dir/
include_dir/file1.txt
include_dir/file2.jpg

sent 296 bytes  received 122 bytes  836,00 bytes/sec
total size is 0  speedup is 0,00

$ tree destination
destination
├── file5.jpg
└── include_dir
    ├── file1.txt
    └── file2.jpg

2 directories, 3 files
```

@WayneD  & @tridge, if you agree that this would be a good addition, please let me know, and I’ll start the process of creating a PR for it.

**Comment by minfrin** [comment]
> I have a work-in-progress tree for this, making it happen as seen below,

This is much appreciated thank you. Lots of automation pain goes away with this.

**Comment by WayneD** [comment]
There's no need for it. It's already supported in the `--filter` option. Just change `--filter-from=FILE` to `-f._FILE`

**Comment by minfrin** [comment]
> There's no need for it. It's already supported in the `--filter` option. Just change `--filter-from=FILE` to `-f._FILE`

I don't see any mention of this -f syntax in the man page, and google isn't showing up anything. What is the significance of the dot and the underscore?

--filter-from is definitely needed to match the pattern of --include-from and --exclude-from.

**Comment by WayneD** [comment]
All the functionality is already there. https://download.samba.org/pub/rsync/rsync.1#opt--filter
